### PR TITLE
Add an endpoint to accept workspace callbacks

### PR DESCRIPTION
**Pull request by jschairb**
This endpoint should be configured as the callback url for any workspaces. There
is a generic model that will store in a collection anything included in the
response body. It also emits the body to a log.

### CODE REVIEW

**Comment by jschairb** [comment]
Do you think I should call them `workspaceEvents`? We might have several different types of events. I could also include a `eventType` and `attributes` fields to make it more abstract. In this particular case the eventType would be `workspace`.

**Review by flazz — APPROVED** [review]

**Comment by flazz** [comment]
i think prefixing is smart, are they workspace events? or workrouting or worker events? not sure.

**Comment by flazz** [comment]
from slack
```
Josh Schairbaum [3:08 PM] 
https://www.twilio.com/console/taskrouter/workspaces/WS0a97843504cc448625dfa55723900216/settings


Franco Lazzarino [3:09 PM] 
i see now, workspaceEvents seems best
```

**Comment by jschairb** [comment]
I rebased after merging your commit. I'm going to merge and test it out.

**Pull request merged**
